# Generated by Django 3.1 on 2020-08-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_url',
            field=models.CharField(max_length=255),
        ),
    ]
