# Generated by Django 3.1 on 2020-08-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
