# Generated by Django 3.1 on 2020-08-24 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company'),
        ('company', '0003_category'),
    ]

    operations = [
    ]
