# Generated by Django 3.1 on 2020-08-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_merge_20200824_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
