name: deploy to firebase

on:
  push:
    branches:
      - main

jobs:
  generate-deploy:
    name: GENERATE and DEPLOY
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        working-directory: ./nuxt
        run: yarn
      - name: Generate static page
        working-directory: ./nuxt
        run: yarn generate
      - name: Deploy to Firebase Hosting
        working-directory: ./nuxt
        run: yarn deploy --token=${{ secrets.FIREBASE_TOKEN }}
